//
//  Artwork+CoreDataClass.swift
//  mona-ios
//
//  Created by Paul Chaffanet on 2019-05-16.
//  Copyright © 2019 Paul Chaffanet. All rights reserved.
//
//

import Foundation
import CoreData

@objc(Artwork)
public class Artwork: NSManagedObject {
    
    @nonobjc public class func fetchRequest(predicate: NSPredicate?, context: NSManagedObjectContext) -> [Artwork] {
        do {
            let fetchRequest : NSFetchRequest<Artwork> = Artwork.fetchRequest()
            fetchRequest.predicate = predicate
            let fetchedResults = try context.fetch(fetchRequest)
            return fetchedResults
        }
        catch {
            log.error("Fetch task failed: \(error)")
            return [Artwork]()
        }
    }
    
    @nonobjc public class func fetchRequest(id: Int16, context: NSManagedObjectContext) -> Artwork? {
        return fetchRequest(predicate: NSPredicate(format: "id = %d", id), context: context).first
    }
    
    // Bug with autogenerated methods in iOS 9
    public func addToPhotos(_ value: Photo) {
        guard let photosOrderedSet = photos else {
            photos = NSOrderedSet(object: value)
            return
        }
        let photosMutableOrderedSet = NSMutableOrderedSet(orderedSet: photosOrderedSet)
        photosMutableOrderedSet.add(value)
        photos = photosMutableOrderedSet
        //value.artwork = self
        NotificationCenter.default.post(name: .didAddPhotoToArtwork, object: nil, userInfo: [
            "photo" : value.localIdentifier,
            "artworkId" : id ])
    }
    
    public func addToPhotos(_ values: [Photo]) {
        
        guard let photosOrderedSet = photos else {
            photos = NSOrderedSet(array: values)
            return
        }
        
        let photosMutableOrderedSet = NSMutableOrderedSet(orderedSet: photosOrderedSet)
        photosMutableOrderedSet.addObjects(from: values)
        photos = photosMutableOrderedSet
        //value.artwork = self
        
        values.forEach {
            NotificationCenter.default.post(name: .didAddPhotoToArtwork, object: nil, userInfo: [
                "photo" : $0.localIdentifier,
                "artworkId" : id ])
        }
        
    }
    
    public func removeFromPhotos(_ value: Photo) {
        guard let photosOrderedSet = photos, photosOrderedSet.contains(value) else {
            return
        }
        
        let photosMutableOrderedSet = NSMutableOrderedSet(orderedSet: photosOrderedSet)
        photosMutableOrderedSet.remove(value)
        photos = photosMutableOrderedSet.count == 0 ? photosMutableOrderedSet : nil
        NotificationCenter.default.post(name: .didRemovePhotoFromArtwork, object: nil, userInfo: [
            "photo" : value.localIdentifier,
            "artworkId" : id ])
    }
    
    public func removeFromPhotos(_ values: [Photo]) {
        // Be sure that photos property is not nil
        guard !values.isEmpty, let photosOrderedSet = photos else {
            return
        }
        // Check which values actually exist in photosOrderedSet.
        // This step is important in order not to avoid post incorrect .didRemovePhotoFromArtwork notifications
        let existingPhotos = values.filter { photo in photosOrderedSet.contains(photo) }
        let photosMutableOrderedSet = NSMutableOrderedSet(orderedSet: photosOrderedSet)
        photosMutableOrderedSet.removeObjects(in: existingPhotos)
        photos = photosMutableOrderedSet.count == 0 ? photosMutableOrderedSet : nil
        
        existingPhotos.forEach { photo in
            NotificationCenter.default.post(name: .didRemovePhotoFromArtwork, object: nil, userInfo: [
                "photo" : photo.localIdentifier,
                "artworkId" : id ])
        }
    }
}
